version: '3'

services:

  books-service:
    build: ./books-service
    image: books-service:latest
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=192.168.1.115:5432
      - DB_USERNAME=admin
      - DB_PASSWORD=admin
      - DB_NAME=boot
      - KAFKA_URI=192.168.1.115:29092
      - spring.profiles.active=prod

  books-stream-service:
    build: ./books-stream-service
    image: books-stream-service:latest
    ports:
      - "8082:8082"
    environment:
      - DB_HOST=192.168.1.115:5432
      - DB_USERNAME=admin
      - DB_PASSWORD=admin
      - DB_NAME=boot
      - KAFKA_URI=192.168.1.115:29092
      - spring.profiles.active=prod


volumes:
  postgres-book-data:
    driver: local