server:
  port: 8081
  servlet:
    context-path: /api

spring:
  profiles:
    active: dev
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/boot"
    username: admin
    password: admin

kafka:
  bootstrapAddress: localhost:29092