spring:
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://${DB_HOST}/${DB_NAME}"
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

kafka:
  bootstrapAddress: ${KAFKA_URI}