server:
  port: 8082
  servlet:
    context-path: /api

spring:
  profiles:
    active: dev
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/boot"
    username: admin
    password: admin
    
kafka:
  bootstrapAddress: localhost:29092